CREATE TABLE IF NOT EXISTS Camera (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  location TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Incident (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cameraId INTEGER NOT NULL,
  type TEXT NOT NULL,
  tsStart TEXT NOT NULL,
  tsEnd TEXT NOT NULL,
  thumbnailUrl TEXT NOT NULL,
  resolved INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (cameraId) REFERENCES Camera(id)
); 